# Lista única das migrações e dos testes de SQL do ensaio (lida por ensaio.sh, rapido.sh e integracao/resetar-banco.sh).
# Ao criar uma migração nova: acrescente aqui (na ordem) e, se ela tiver teste, o teste em TESTES_SQL.
# Cada migração roda em uma execução separada (a 020 e a 027 precisam disso: valores novos de enum).
MIGRACOES=(
  020_banco_talentos_tipos.sql
  021_banco_talentos_modelo.sql
  022_banco_talentos_regras.sql
  023_banco_talentos_sanitizacao.sql
  024_banco_talentos_views.sql
  025_banco_talentos_migracao_dados.sql
  026_banco_talentos_ajustes.sql
  027_banco_talentos_tipos2.sql
  028_banco_talentos_etapa1.sql
  029_banco_talentos_etapa2.sql
  030_banco_talentos_etapa3.sql
  031_qualificacao_curriculo.sql
  032_email_de_envio.sql
  033_selecao_por_qualificacao.sql
  034_atribuir_grava_qualificacao.sql
  035_catalogo_setores_cargos_niveis.sql
  036_niveis_habilitar_desabilitar.sql
  037_candidatos_da_vaga_views.sql
  038_selecao_por_loja.sql
  039_link_do_curriculo_na_excecao.sql
  040_horario_e_pausa_da_ia.sql
  041_sexo_pelo_nome.sql
  042_historico_candidato.sql
  043_sanitizacao_um_mes.sql
  044_bloqueios_nome.sql
  045_filtro_sexo_dos_selecionados.sql
  046_status_do_robo.sql
  047_sanitizacao_so_inativa_expurgo_automatico.sql
  048_filtros_email_telefone_cargos.sql
  049_selecao_mais_filtros.sql
  050_gerente_loja_tipos.sql
  051_gerente_loja.sql
  052_historico_no_banco.sql
  053_opcoes_cidade.sql
  054_loja_capital_atacadista.sql
  055_encaminhar_gerente_whatsapp.sql
  056_message_id_sem_controle.sql
  057_encaminhar_gerente_cr.sql
  058_gerente_nome.sql
  059_sigla_capital.sql
  060_mensagem_gerente_quebra_linha.sql
  061_operador_empilhadeira.sql
  062_selecao_varias_cidades.sql
  063_dashboard_cvs_por_regiao.sql
  064_dashboard_cvs_serie.sql
  065_dashboard_entrevistas_contratacoes.sql
  066_revisao_sem_nivel_vira_junior.sql
  069_caixa_emails_dia.sql
  070_contratar_candidatura.sql
  071_emails_ignorados.sql
)
# Testes que rodam sobre o banco já migrado (cada um termina em ROLLBACK)
TESTES_SQL=(
  ensaio/10_teste_regras.sql
  ensaio/11_teste_sanitizacao.sql
  ensaio/14_teste_etapa1.sql
  ensaio/15_teste_etapa2.sql
  ensaio/16_teste_etapa3.sql
  ensaio/17_teste_qualificacao.sql
  ensaio/18_teste_email_de_envio.sql
  ensaio/19_teste_selecao.sql
  ensaio/21_teste_niveis.sql
  ensaio/22_teste_link_curriculo.sql
  ensaio/23_teste_pausa_ia.sql
  ensaio/24_teste_sexo_pelo_nome.sql
  ensaio/25_teste_historico.sql
  ensaio/26_teste_status_do_robo.sql
  ensaio/27_teste_expurgo_automatico.sql
  ensaio/28_teste_filtros_email_telefone_cargos.sql
  ensaio/29_teste_selecao_mais_filtros.sql
  ensaio/30_teste_gerente_loja.sql
  ensaio/31_teste_historico_no_banco.sql
  ensaio/32_teste_opcoes_cidade.sql
  ensaio/33_teste_message_id_seguro.sql
  ensaio/34_teste_contratar.sql
)
